import = [
    #"~/.config/alacritty/themes/themes/ayu_dark.toml"
    "~/.config/alacritty/themes/themes/base16_default_dark.toml"
]

#shell.program = "/usr/bin/tmux"
live_config_reload = true

[window]
padding = { x = 15, y = 15 }
opacity = 1

# [cursor]
# style = { shape = "Beam", blinking = "Off"}

[font]
size = 8
# "Fira Code", "JetBrainsMono Nerd Font", "MesloLGL Nerd Font", "Iosevka (Nerd Font/Comfy Wide)", ""
#normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular"}
#bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold"}
#normal = { family = "FiraMono Nerd Font", style = "Regular" }
#normal = { family = "Ubuntu Mono", style = "SemiBold"}
normal = { family = "BigBlueTerm437 Nerd Font",style = "Regular" }

[colors.primary]
#background = '#0A0E14'
#background = "#181a18" # gray background
#background = "#0c0e0c"
background = "#1B1C1E"
#background = "#131421"
#background = "#101010"
#background = "#11111b" # catppuccin blue FOR TRANSPARENCY
foreground = '#B3B1AD'
